export const INIT = {
  newTask: {
    name: '',
    description: '',
    assignees: [],
    tags: [],
    status: [],
    priority: [],
    due_date: [],
    due_date_time: false,
    time_estimate: [],
    start_date: [],
    start_date_time: false,
    notify_all: false,
    parent: null,
    links_to: null,
    check_required_custom_fields: false,
    custom_fields: [],
  },
  updateTask: {
    name: '',
    description: '',
    status: '',
    priority: [],
    due_date: [],
    due_date_time: false,
    time_estimate: [],
    start_date: [],
    start_date_time: false,
    parent: '',
    assignees: {},
    achived: false,
  },
}
